export enum ResFont {
    poppinsMedium = "Poppins-Medium",
    poppinsSemiBold = "Poppins-SemiBold",
    poppinsBold = "Poppins-Bold",
    poppinsMediumItalic = "Poppins-MediumItalic",
    poppinsSemiBoldItalic = "Poppins-SemiBoldItalic",
    poppinsBoldItalic = "Poppins-BoldItalic",
    circularMedium = "CircularStd-Medium",
    circularBold = "CircularStd-Bold",
    circularBlack = "CircularStd-Black",
    circularMediumItalic = "CircularStd-MediumItalic",
    circularBoldItalic = "CircularStd-BoldItalic",
    circularBlackItalic = "CircularStd-BlackItalic",
    plexMonoMedium = "IBMPlexMono-Medium",
    plexMonoSemiBold = "IBMPlexMono-SemiBold",
    plexMonoBold = "IBMPlexMono-Bold",
    plexMonoMediumItalic = "IBMPlexMono-MediumItalic",
    plexMonoSemiBoldItalic = "IBMPlexMono-SemiBoldItalic",
    plexMonoBoldItalic = "IBMPlexMono-BoldItalic",
    gilroyExtraBold = "Gilroy-ExtraBold",
}
